route:
  group_by: ['alertname', 'builder', 'relay', 'chain']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 2h
  receiver: 'discord'

receivers:
- name: 'discord'
  webhook_configs:
  - url: '${ALERT_WEBHOOK}'   # set in docker-compose env
    send_resolved: true
